version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
  web:
    build: ./php/
    container_name: php_web
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: secret
